OctopusStore/ViewModels/Item/ItemCreateViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace OctopusStore.ViewModels
{
    public class ItemCreateViewModel : ItemViewModel
    {
        public ItemCreateViewModel()
            : base()
        {
        }
        public ItemCreateViewModel(ItemViewModel vm)
            : base(vm)
        {
        }

        [BindProperty]
        public IEnumerable<SelectListItem> Brands { get; set; }
        [BindProperty]
        public IEnumerable<SelectListItem> Categories { get; set; }
        [BindProperty]
        public IEnumerable<SelectListItem> Stores { get; set; }
        [BindProperty]
        public IEnumerable<SelectListItem> MeasurementUnits { get; set; }
    }
}

OctopusStore/ViewModels/Item/ItemDeleteViewModel.cs
namespace OctopusStore.ViewModels
{
    public class ItemDeleteViewModel : ItemViewModel
    {
        public ItemDeleteViewModel() 
            : base()
        {
        }

        public ItemDeleteViewModel(ItemViewModel vm)
            : base(vm)
        {
        }
    }
}

OctopusStore/ViewModels/Item/ItemDetailViewModel.cs
namespace OctopusStore.ViewModels
{
    public class ItemDetailsViewModel : ItemViewModel
    {
        public ItemDetailsViewModel() : base()
        {
        }
        public ItemDetailsViewModel(ItemViewModel vm) : base(vm)
        {
        }
    }
}

OctopusStore/ViewModels/Item/ItemEditViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace OctopusStore.ViewModels
{
    public class ItemEditViewModel : ItemViewModel
    {
        public ItemEditViewModel()
            : base()
        {
        }
        public ItemEditViewModel(ItemViewModel vm)
            : base(vm)
        {
        }

        [BindProperty]
        public IEnumerable<SelectListItem> Brands { get; set; }
        [BindProperty]
        public IEnumerable<SelectListItem> Categories { get; set; }
        //[BindProperty]
        public IEnumerable<SelectListItem> Stores { get; set; }
        [BindProperty]
        public IEnumerable<SelectListItem> MeasurementUnits { get; set; }
        public int ImageIdToRemove { get; set; }
    }
}

OctopusStore/ViewModels/Item/ItemImage/ItemImageCreateViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Internal;
using System.IO;

namespace OctopusStore.ViewModels
{
    public class ItemImageCreateViewModel : ItemImageViewModel
    {
        public ItemImageCreateViewModel(int itemId)
        {
            this.ItemId = itemId;
        }
        public ItemImageCreateViewModel()
        {
        }
        public IFormFile ImageFormFile { get; set; }
        public byte[] ImageBytes { get; set; }

    }
}

OctopusStore/ViewModels/Item/ItemImage/ItemImageDetailViewModel.cs
namespace OctopusStore.ViewModels
{
    public class ItemImageDetailViewModel : ItemImageViewModel
    {
        public byte[] ImageByte { get; set; }
    }
}

OctopusStore/ViewModels/Item/ItemImage/ItemImageEditViewModel.cs
namespace OctopusStore.ViewModels
{
    public class ItemImageEditViewModel : ItemImageViewModel
    {
    }
}

OctopusStore/ViewModels/Item/ItemImage/ItemImageViewModel.cs
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Mvc;

namespace OctopusStore.ViewModels
{
    public class ItemImageViewModel
    {
        [BindProperty]
        public int Id { get; set; }
        public string Title { get; set; }
        public int ItemId { get; set; }
        public string ContentType { get; set; }

        public static ItemImageViewModel FromItemImage(FileDetails<Item> imageItem)
        {
            return new ItemImageViewModel
            {
                Id = imageItem.Id,
                ItemId = imageItem.RelatedId,
                Title = imageItem.Title
            };
        }
    }
}

OctopusStore/ViewModels/Item/ItemIndexViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace OctopusStore.ViewModels
{
    public class ItemIndexViewModel
    {
        public IEnumerable<ItemViewModel> Items { get; set; }
        public IEnumerable<SelectListItem> Brands { get; set; }
        public IEnumerable<SelectListItem> Categories { get; set; }
        public int? BrandFilterApplied { get; set; }
        public int? CategoryFilterApplied { get; set; }
        public PaginationInfoViewModel PaginationInfo { get; set; }
    }
}

OctopusStore/ViewModels/Item/ItemViewModel.cs
using ApplicationCore.Entities;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OctopusStore.ViewModels
{
    public class ItemViewModel
    {
        public ItemViewModel()
        {
        }
        public ItemViewModel(ItemViewModel vm)
        {
            Id = vm.Id;
            Title = vm.Title;
            CategoryId = vm.CategoryId;
            Category = vm.Category;
            BrandId = vm.BrandId;
            Brand = vm.Brand;
            MeasurementUnitId = vm.MeasurementUnitId;
            MeasurementUnit = vm.MeasurementUnit;
            Price = vm.Price;
            Description = vm.Description;
            StoreId = vm.StoreId;
            Store = vm.Store;
            ImageViewModels = vm.ImageViewModels;
        }
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false)]
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public int StoreId { get; set; }
        public int BrandId { get; set; }
        public int MeasurementUnitId { get; set; }
        public string Description { get; set; }
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        public IEnumerable<ItemImageViewModel> ImageViewModels { get; set; }

        public Category Category { get; set; }
        public Store Store { get; set; }
        public Brand Brand { get; set; }
        public MeasurementUnit MeasurementUnit { get; set; }
    }
}

OctopusStore/Controllers/ImagesController.cs
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using OctopusStore.Interfaces;
using OctopusStore.ViewModels;
using System;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;

namespace OctopusStore.Controllers
{
    public class ImagesController : Controller
    {
        private readonly IItemService _itemService;
        public ImagesController(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task<ActionResult> Get(int id)
        {
            var image = await _itemService.GetItemImageDetailViewModelAsync(id);
            if (image != null)
            {
                return Get(image);
            }
            return File(new byte[0], "image/jpeg");
        }
        public async Task<ActionResult> Delete(ItemImageViewModel viewModel)
        {
            await _itemService.DeleteItemImageAsync(viewModel);
            return Redirect($"~/Item/Edit/{viewModel.ItemId}");
        }
        public async Task<ActionResult> Create(ItemImageCreateViewModel viewModel, ModelStateDictionary modelState)
        {
            IFormFile formFile = viewModel.ImageFormFile;
            var fieldDisplayName = string.Empty;

            MemberInfo property = typeof(ItemImageCreateViewModel).GetProperty(formFile.Name.Substring(formFile.Name.IndexOf(".") + 1));
            if (property != null)
            {
                var displayAttribute = property.GetCustomAttribute(typeof(DisplayAttribute)) as DisplayAttribute;

                if (displayAttribute != null)
                {
                    fieldDisplayName = $"{displayAttribute.Name}";
                }
            }
            var fileName = WebUtility.HtmlEncode(Path.GetFileName(formFile.FileName));
            string contentType = formFile.ContentType.ToLower();
            if (contentType != "image/jpeg" && contentType != "image/png")
            {
                modelState.AddModelError(formFile.Name,
                                         $"The {fieldDisplayName}file ({fileName}) must be an image file.");
            }

            if (formFile.Length == 0)
            {
                modelState.AddModelError(formFile.Name, $"The {fieldDisplayName}file ({fileName}) is empty.");
            }
            else if (formFile.Length > 10 * 1024 * 1024)
            {
                modelState.AddModelError(formFile.Name, $"The {fieldDisplayName}file ({fileName}) exceeds 10 MB.");
            }
            else
            {
                try
                {
                    byte[] fileContents = new byte[formFile.Length];
                    using (var reader = formFile.OpenReadStream())
                    {
                        int read = await reader.ReadAsync(fileContents, 0, (int)formFile.Length);

                        if (fileContents.Length == read)
                        {
                            viewModel.ImageBytes = fileContents;
                            viewModel.ContentType = contentType;
                            viewModel.Title = fileName;

                            var image = await _itemService.CreateItemImageAsync(viewModel);
                            if (image != null)
                            {
                                return Redirect($"/Item/Edit/{viewModel.ItemId}");
                            }
                            return Redirect($"/Item/Edit/{viewModel.ItemId}");
                        }
                        else
                        {
                            modelState.AddModelError(formFile.Name,
                                                     $"The {fieldDisplayName}file ({fileName}) is empty.");
                        }
                    }
                }
                catch (Exception ex)
                {
                    modelState.AddModelError(formFile.Name,
                                             $"The {fieldDisplayName}file ({fileName}) upload failed. " +
                                             $"Please contact the Help Desk for support. Error: {ex.Message}");
                }
            }
            return Redirect($"/Item/Edit/{viewModel.ItemId}");
        }

        private ActionResult Get(ItemImageDetailViewModel image)
        {
            return File(image.ImageByte, image.ContentType);
        }
    }
}

OctopusStore/Pages/Item/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OctopusStore.Interfaces;
using OctopusStore.ViewModels;
using System.Threading.Tasks;

namespace OctopusStore.Pages.Item
{
    public class CreateModel : PageModel
    {
        private readonly IItemService _itemService;
        [BindProperty]
        public ItemCreateViewModel ItemModel { get; set; }

        public CreateModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task OnGet(ItemCreateViewModel itemModel)
        {
            ItemModel = await _itemService.GetCreateViewModelAsync();
        }

        public async Task <IActionResult> OnPost(ItemCreateViewModel itemModel)
        {
            if (!ModelState.IsValid)
            {
                await _itemService.GetCreateViewModelAsync(this.ItemModel);
                return Page();
            }
            var item = _itemService.CreateItemAsync(itemModel);

            return RedirectToPage("./Index");
        }
    }
}

OctopusStore/Pages/Item/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OctopusStore.Interfaces;
using OctopusStore.ViewModels;

namespace OctopusStore.Pages.Item
{
    public class DeleteModel : PageModel
    {
        private readonly IItemService _itemService;
        [BindProperty]
        public ItemDeleteViewModel ItemModel { get; set; }

        public DeleteModel(IItemService itemService)
        {
            _itemService = itemService;
        }



        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ItemModel = await _itemService.GetItemDeleteViewModelAsync(id.Value);

            if (ItemModel == null)
            {
                return NotFound();
            }
            return Page();
        }

        public IActionResult OnPost(int? id)
        {
            if (ItemModel == null)
            {
                return NotFound();
            }

           _itemService.DeleteItemAsync(ItemModel);
            return RedirectToPage("./Index");
        }
    }
}

OctopusStore/Pages/Item/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OctopusStore.Interfaces;
using OctopusStore.ViewModels;
using System.Threading.Tasks;

namespace OctopusStore.Pages.Item
{
    public class DetailsModel : PageModel
    {
        private readonly IItemService _itemService;
        [BindProperty]
        public ItemDetailsViewModel ItemModel { get; set; }

        public DetailsModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ItemModel = await _itemService.GetItemDetailsViewModelAsync(id.Value);

            if (ItemModel == null)
            {
                return NotFound();
            }
            return Page();
        }

    }
}

OctopusStore/Pages/Item/Edit.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OctopusStore.Interfaces;
using OctopusStore.ViewModels;

namespace OctopusStore.Pages.Item
{
    public class EditModel : PageModel
    {
        private readonly IItemService _itemService;
        [BindProperty]
        public ItemEditViewModel ItemModel { get; set; }
        public SelectList list { get; set; }

        public EditModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ItemModel = await _itemService.GetItemEditViewModelAsync(id.Value);


            if (ItemModel == null)
            {
                return NotFound();
            }


            return Page();
        }

        public async Task<IActionResult> OnPost(ItemEditViewModel itemModel)
        {
            if (!ModelState.IsValid)
            {
                await _itemService.GetItemEditViewModelAsync(itemModel.Id, this.ItemModel);
                return Page();
            }
             await _itemService.UpdateItemAsync(itemModel);

            return RedirectToPage("./Index");
        }
    }
}

OctopusStore/Pages/Item/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OctopusStore.Interfaces;
using OctopusStore.ViewModels;

namespace OctopusStore.Pages.Item
{
    public class IndexModel : PageModel
    {
        private readonly IItemService _itemService;

        public IndexModel(IItemService itemService)
        {
            _itemService = itemService;
        }
        public ItemIndexViewModel ItemModel { get; set; } = new ItemIndexViewModel();

        public async Task OnGet(ItemIndexViewModel itemModel, int? pageId)
        {
            ItemModel = await _itemService.GetItems(pageId ?? 0, Constants.ITEMS_PER_PAGE, itemModel.CategoryFilterApplied, itemModel.BrandFilterApplied);
        }
    }
}

OctopusStore/Pages/Item/Create.cshtml
@page
@model Pages.Item.CreateModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ItemModel.Title" class="control-label"></label>
                <input asp-for="ItemModel.Title" class="form-control" />
                <span asp-validation-for="ItemModel.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.Category" class="control-label"></label>
                <select asp-for="ItemModel.CategoryId" class="form-control" asp-items="Model.ItemModel.Categories"></select>
                <span asp-validation-for="ItemModel.CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.Store" class="control-label"></label>
                <select asp-for="ItemModel.StoreId" class="form-control" asp-items="Model.ItemModel.Stores"></select>
                <span asp-validation-for="ItemModel.StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.Brand" class="control-label"></label>
                <select asp-for="ItemModel.BrandId" class="form-control" asp-items="Model.ItemModel.Brands"></select>
                <span asp-validation-for="ItemModel.BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.MeasurementUnit" class="control-label"></label>
                <select asp-for="ItemModel.MeasurementUnitId" class="form-control" asp-items="Model.ItemModel.MeasurementUnits"></select>
                <span asp-validation-for="ItemModel.MeasurementUnitId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.Description" class="control-label"></label>
                <input asp-for="ItemModel.Description" class="form-control" />
                <span asp-validation-for="ItemModel.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.Price" class="control-label"></label>
                <input asp-for="ItemModel.Price" class="form-control" />
                <span asp-validation-for="ItemModel.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OctopusStore/Pages/Item/Delete.cshtml
@page "{id:int?}"
@model DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Brand)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Brand.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Category.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.MeasurementUnit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.MeasurementUnit.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Store)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Store.Title)
        </dd>
    </dl>
    <div>
        @foreach (var itemImage in Model.ItemModel.ImageViewModels)
        {
            Html.RenderPartial("ItemImage/_itemImageDetail", itemImage);
        }
    </div>
    <form method="post">
        <input type="hidden" asp-for="ItemModel.Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

OctopusStore/Pages/Item/Details.cshtml
@page "{id:int?}"
@model DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Brand)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Brand.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Category.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.MeasurementUnit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.MeasurementUnit.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemModel.Store)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemModel.Store.Title)
        </dd>
    </dl>
    <div>
        @foreach (var itemImage in Model.ItemModel.ImageViewModels)
        {
            Html.RenderPartial("ItemImage/_itemImageDetail", itemImage);
        }
    </div>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", "Item", new { id = Model.ItemModel.Id })
    @Html.ActionLink("Index", "Index", "Item")
</div>

OctopusStore/Pages/Item/Edit.cshtml
@page "{id:int?}"
@model EditModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="ItemModel.Id" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.Title" class="control-label"></label>
                <input asp-for="ItemModel.Title" class="form-control" />
                <span asp-validation-for="ItemModel.Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ItemModel.Category" class="control-label"></label>
                <select asp-for="ItemModel.CategoryId" class="form-control" asp-items="Model.ItemModel.Categories"></select>
                <span asp-validation-for="ItemModel.CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ItemModel.Brand" class="control-label"></label>
                <select asp-for="ItemModel.BrandId" class="form-control" asp-items="Model.ItemModel.Brands"></select>
                <span asp-validation-for="ItemModel.BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.MeasurementUnit" class="control-label"></label>
                <select asp-for="ItemModel.MeasurementUnitId" class="form-control" asp-items="Model.ItemModel.MeasurementUnits"></select>
                <span asp-validation-for="ItemModel.MeasurementUnitId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.StoreId" class="control-label"></label>
                <select asp-for="ItemModel.StoreId" class="form-control" asp-items="Model.ItemModel.Stores"></select>
                <span asp-validation-for="ItemModel.StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.Description" class="control-label"></label>
                <input asp-for="ItemModel.Description" class="form-control" />
                <span asp-validation-for="ItemModel.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemModel.Price" class="control-label"></label>
                <input asp-for="ItemModel.Price" class="form-control" />
                <span asp-validation-for="ItemModel.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
        <div>
            @{ 
                Html.RenderPartial("itemImage/_itemImageCreate", new ItemImageCreateViewModel(Model.ItemModel.Id));
            }
        </div>
        <div>
           @if (Model.ItemModel.ImageViewModels != null && Model.ItemModel.ImageViewModels.Any())
           {
               foreach(var imageViewModel in Model.ItemModel.ImageViewModels)
               {
                   Html.RenderPartial("ItemImage/_itemImageEdit", imageViewModel);

               }
           }
        </div>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OctopusStore/Pages/Item/Index.cshtml
@page "{id:int?}"
@{
    ViewData["Title"] = "Catalog";
    @model IndexModel
}
<div class="container-fluid">
    <div class="row">
        <section>
            <div class="index-navigation">
                <form method="get">
                    <label data-title="brand">
                        <select asp-for="@Model.ItemModel.CategoryFilterApplied" asp-items="@Model.ItemModel.Categories"></select>
                    </label>
                    <label data-title="brand">
                        <select asp-for="@Model.ItemModel.BrandFilterApplied" asp-items="@Model.ItemModel.Brands"></select>
                    </label>
                    <input type="submit" value="Filter" />
                </form>
            </div>
        </section>
    </div>
    <div class="row">
        <section id="all-items">
            <div class="container">
                @if (Model.ItemModel.Items.Any())
            {
                @Html.Partial("_pagination", Model.ItemModel.PaginationInfo)

                <div class="row">
                    @foreach (var item in Model.ItemModel.Items)
                {
                    <div class="col-md-4 item-card">
                        @Html.Partial("_indexItem", item)
                    </div>
            }
                </div>
                @Html.Partial("_pagination", Model.ItemModel.PaginationInfo)
        }
        else
        {
            <div class="esh-catalog-item row">
                There are no results that match you search
            </div>

        }
            </div>
        </section>

    </div>
</div>

OctopusStore/Pages/Item/_indexItem.cshtml
@model ViewModels.ItemViewModel


    <form asp-page="/Basket/Index" method="post">
        <div>
            <div class="item-card-image">
                @if (Model.ImageViewModels != null && Model.ImageViewModels.Any())
                {
                <img src="@Url.Action("Get", "Images", new { id = Model.ImageViewModels.ElementAt(0).Id })" />
                }
            </div>
            <div class="item-card-description">
                <div>
                    <span>@Model.Title</span>
                </div>
                <div>
                    <span>@Model.Price.ToString("N2")</span>
                </div>
                <div>
                    <span>@Model.Description</span>
                </div>
                <a asp-page="../Item/Details" asp-route-id="@Model.Id">Details</a>
                <input type="submit" value="[ADD TO BASKET]" />
            </div>

        </div>
        <input type="hidden" asp-for="@Model.Id" name="id" />
        <input type="hidden" asp-for="@Model.Title" name="title" />
        <input type="hidden" asp-for="@Model.Price" name="price" />
        <input type="hidden" asp-for="@Model.Description" name="description" />

    </form>